# -*- coding: utf-8 -*-
"""Weather Forecasting

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/12iRS5oynnJsoCskNFAWVePUVjOC1e2Wn

#WEATHER FORECASTING USING PYTHON

##Import the libraries
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import plotly.express as px

"""##Read the dataset"""

dataset = pd.read_csv("/content/drive/MyDrive/DailyDelhiClimateTrain.csv")
print(dataset.head())

print(dataset.describe())

print(dataset.info())

temp = px.line(dataset,x="date",y="meantemp",title = "Mean Temperature in Delhi over the years")
temp.show()

temp = px.line(dataset,x="date",y="humidity",title = "Humidity in Delhi over the years")
temp.show()

temp = px.line(dataset,x="date",y="wind_speed",title = "Wind speed in Delhi over the years")
temp.show()

temp = px.scatter(data_frame = dataset,x="humidity",y="meantemp",size="meantemp",trendline="ols",title="Relationship between temperature and humidity")
temp.show()

dataset["date"]=pd.to_datetime(dataset["date"],format='%Y-%m-%d')
dataset["year"]=dataset["date"].dt.year
dataset["month"]=dataset["date"].dt.month
print(dataset.head())

plt.style.use('fivethirtyeight')
plt.figure(figsize=(15,10))
plt.title("Temperature change in Delhi over the years")
sns.lineplot(data=dataset,x='month',y='meantemp',hue='year')
plt.show()

"""##Forecasting weather using python"""

pip install prophet

forecast_data = dataset.rename(columns={"date":"ds","meantemp":"y"})
print(forecast_data)

from prophet import Prophet
from prophet.plot import plot_plotly,plot_components_plotly
model = Prophet()
model.fit(forecast_data)
forecasts = model.make_future_dataframe(periods=365)
predictions = model.predict(forecasts)
plot_plotly(model,predictions)